import os
import csv
import re

# File Paths
DOWNLOADS_DIR = r"C:\Users\Dr. Yogesh\Downloads"
TABLE_SCHEMA_PATH = os.path.join(DOWNLOADS_DIR, "table schema.txt")
PKEY_CSV_PATH = os.path.join(DOWNLOADS_DIR, "Supabase Snippet Untitled query (1).csv")
FKEY_CSV_PATH = os.path.join(DOWNLOADS_DIR, "Supabase Snippet Untitled query (2).csv")
INDEX_CSV_PATH = os.path.join(DOWNLOADS_DIR, "Supabase Snippet Untitled query.csv")
MIGRATIONS_DIR = r"c:\Users\Dr. Yogesh\Videos\APP FOLDER - V1 - Copy\app\frontend-noji-2.6.2\3\pilot pro 10.2\supabase\migrations"
MIGRATIONS_EXTRA_SQL_DIR = r"c:\Users\Dr. Yogesh\Videos\APP FOLDER - V1 - Copy\app\frontend-noji-2.6.2\3\pilot pro 10.2\supabase"

OUTPUT_SQL_PATH = r"c:\Users\Dr. Yogesh\Videos\APP FOLDER - V1 - Copy\app\frontend-noji-2.6.2\3\pilot pro 10.2\recreate_schema.sql"

def parse_csv_ddl(csv_path):
    ddls = []
    if not os.path.exists(csv_path):
        print(f"Warning: {csv_path} not found.")
        return ddls
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader, None) # skip header
        for row in reader:
            if row:
                line = row[0].strip()
                # Clean enclosing quotes if any
                if (line.startswith('"') and line.endswith('"')) or (line.startswith("'") and line.endswith("'")):
                    line = line[1:-1].strip()
                if line:
                    ddls.append(line)
    return ddls

def main():
    print("Compiling database schema...")
    
    # Collect files from migration directory and local sql files
    migration_files = []
    if os.path.exists(MIGRATIONS_DIR):
        for f in sorted(os.listdir(MIGRATIONS_DIR)):
            if f.endswith('.sql'):
                migration_files.append(os.path.join(MIGRATIONS_DIR, f))
                
    # Also collect SOFTNOTES_MIGRATION.sql, overhaul_v2.sql, etc.
    extra_files = ["SOFTNOTES_MIGRATION.sql", "overhaul_v2.sql", "flashcards_v2.sql", "flashcards_v3_srs_overhaul.sql", "analytics_upgrade.sql"]
    for f in extra_files:
        path = os.path.join(MIGRATIONS_EXTRA_SQL_DIR, f)
        if os.path.exists(path):
            migration_files.append(path)

    # Discover any views defined in migrations
    discovered_views = set()
    for file_path in migration_files:
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            matches = re.findall(r'(?i)CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+(?:public\.)?([a-zA-Z0-9_]+)', content)
            for m in matches:
                discovered_views.add(m.lower())
        except Exception as e:
            print(f"Warning scanning views in {os.path.basename(file_path)}: {e}")
            
    print(f"Discovered views: {discovered_views}")
    
    # 1. Extensions
    sql_sections = []
    sql_sections.append("-- ==================================================\n-- 1. EXTENSIONS\n-- ==================================================\n")
    sql_sections.append('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\nCREATE EXTENSION IF NOT EXISTS "pgcrypto";\n')

    # 2. Table definitions from table schema.txt
    sql_sections.append("\n-- ==================================================\n-- 2. CREATE TABLES (Base Columns Only)\n-- ==================================================\n")
    created_tables = set()
    if os.path.exists(TABLE_SCHEMA_PATH):
        with open(TABLE_SCHEMA_PATH, 'r', encoding='utf-8') as f:
            content = f.read()
        # Each CREATE TABLE statement is separated by lines
        statements = [s.strip() for s in content.split('\n') if s.strip()]
        for stmt in statements:
            # Ensure it ends with a semicolon
            if not stmt.endswith(';'):
                stmt += ';'
                
            # Extract table name to check if it's actually a view
            match = re.search(r'(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?([a-zA-Z0-9_]+)', stmt)
            tbl_name = match.group(1).lower() if match else ""
            if tbl_name in discovered_views:
                print(f"Skipping table creation for '{tbl_name}' as it is a VIEW defined in migrations.")
                continue
                
            # Convert CREATE TABLE to CREATE TABLE IF NOT EXISTS for safety
            if "IF NOT EXISTS" not in stmt.upper():
                stmt_clean = re.sub(r'(?i)CREATE\s+TABLE\s+([a-zA-Z0-9_\.]+)', r'CREATE TABLE IF NOT EXISTS \1', stmt)
            else:
                stmt_clean = stmt
            # Fix invalid 'ARRAY' types generated by the information_schema query
            stmt_clean = re.sub(r'\bARRAY\b', 'text[]', stmt_clean)
            # Ensure question_number is created as TEXT (matching local migrations)
            stmt_clean = re.sub(r'\bquestion_number\s+integer\b', 'question_number text', stmt_clean)
            sql_sections.append(stmt_clean + "\n")
            
            # Record table name to prevent duplicate creation
            match = re.search(r'(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?([a-zA-Z0-9_]+)', stmt_clean)
            if match:
                created_tables.add(match.group(1).lower())
    else:
        print("Error: Table schema file not found.")
        return

    # 3. Primary keys from CSV (with composite key fix for folder_algorithm_settings)
    sql_sections.append("\n-- ==================================================\n-- 3. PRIMARY KEYS\n-- ==================================================\n")
    pkey_lines = parse_csv_ddl(PKEY_CSV_PATH)
    
    has_folder_algo_settings_pkeys = []
    other_pkeys = []
    for line in pkey_lines:
        if "folder_algorithm_settings" in line:
            has_folder_algo_settings_pkeys.append(line)
        else:
            if not line.endswith(';'):
                line += ';'
            other_pkeys.append(line)
            
    for pkey in other_pkeys:
        sql_sections.append(pkey + "\n")
        
    # Write composite primary key for folder_algorithm_settings
    if has_folder_algo_settings_pkeys:
        sql_sections.append("ALTER TABLE folder_algorithm_settings ADD PRIMARY KEY (user_id, folder_key);\n")

    # 4. Indexes (filtering out auto-generated pkey indexes)
    sql_sections.append("\n-- ==================================================\n-- 4. INDEXES\n-- ==================================================\n")
    index_lines = parse_csv_ddl(INDEX_CSV_PATH)
    for line in index_lines:
        # Skip auto-created primary key indexes
        if "_pkey" in line.lower() or "unique_user_cards_user_card" in line.lower():
            continue
        if not line.endswith(';'):
            line += ';'
        sql_sections.append(line + "\n")

    # 5. Foreign Keys
    sql_sections.append("\n-- ==================================================\n-- 5. FOREIGN KEYS\n-- ==================================================\n")
    fkey_lines = parse_csv_ddl(FKEY_CSV_PATH)
    for line in fkey_lines:
        if not line.endswith(';'):
            line += ';'
        sql_sections.append(line + "\n")

    # 6. RLS Policies, views, triggers, and functions from local migrations
    sql_sections.append("\n-- ==================================================\n-- 6. VIEWS, FUNCTIONS, TRIGGERS & RLS POLICIES (From Local Migrations)\n-- ==================================================\n")
    
    # We will walk through migrations and extract:
    # - ALTER TABLE ... ENABLE ROW LEVEL SECURITY
    # - CREATE POLICY ...
    # - CREATE OR REPLACE VIEW ...
    # - CREATE OR REPLACE FUNCTION ...
    # - CREATE TRIGGER ...
    # - Any INSERT SEED DATA
    
    processed_statements = set()
    
    for file_path in migration_files:
        print(f"Reading migrations from {os.path.basename(file_path)}...")
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
            
        # Parse statements using a simple heuristic: split by semicolon
        # However, we must be careful with PL/pgSQL function definitions containing semicolons inside $$ blocks.
        # Let's split by semicolon, but ignore those inside $$ ... $$
        
        statements = []
        current_stmt = []
        in_dollar_block = False
        dollar_tag = ""
        
        lines = content.split('\n')
        for line in lines:
            # Check for dollar quoting like $$ or $body$ or $function$
            if not in_dollar_block:
                match = re.search(r'\$[a-zA-Z_]*\$', line)
                if match:
                    in_dollar_block = True
                    dollar_tag = match.group(0)
            else:
                if dollar_tag in line:
                    in_dollar_block = False
                    dollar_tag = ""
            
            current_stmt.append(line)
            if ';' in line and not in_dollar_block:
                # Splitting logic on semicolon
                stmt_text = '\n'.join(current_stmt).strip()
                if stmt_text:
                    statements.append(stmt_text)
                current_stmt = []
                
        if current_stmt:
            stmt_text = '\n'.join(current_stmt).strip()
            if stmt_text:
                statements.append(stmt_text)

        # Filter and append statements
        for stmt in statements:
            stmt_upper = stmt.upper()
            
            # We want to extract:
            # - ENABLE ROW LEVEL SECURITY
            # - CREATE POLICY / DROP POLICY
            # - CREATE VIEW / CREATE OR REPLACE VIEW
            # - CREATE FUNCTION / CREATE OR REPLACE FUNCTION
            # - CREATE TRIGGER / DROP TRIGGER
            # - INSERT INTO seed data
            # - GRANT SELECT / COMMENT ON
            
            is_target = any(k in stmt_upper for k in [
                "ROW LEVEL SECURITY", "POLICY", "VIEW", "FUNCTION", "TRIGGER", 
                "INSERT INTO", "GRANT", "COMMENT ON", "CREATE TABLE"
            ])
            
            is_alter_column = "ADD COLUMN" in stmt_upper or "DROP COLUMN" in stmt_upper
            
            if is_target and not is_alter_column:
                # Special handling for CREATE TABLE
                if "CREATE TABLE" in stmt_upper:
                    match = re.search(r'(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?([a-zA-Z0-9_]+)', stmt)
                    if match:
                        tbl_name = match.group(1).lower()
                        if tbl_name in created_tables:
                            # Table is already defined in Section 2, skip it
                            continue
                        else:
                            # Table was missing from Section 2, so define it here
                            if "IF NOT EXISTS" not in stmt_upper:
                                stmt_clean = re.sub(r'(?i)CREATE\s+TABLE\s+([a-zA-Z0-9_\.]+)', r'CREATE TABLE IF NOT EXISTS \1', stmt.strip())
                            else:
                                stmt_clean = stmt.strip()
                            stmt_clean = re.sub(r'\bARRAY\b', 'text[]', stmt_clean)
                            if stmt_clean not in processed_statements:
                                processed_statements.add(stmt_clean)
                                created_tables.add(tbl_name)
                                sql_sections.append(stmt_clean + "\n\n")
                            continue
                
                # Prevent exact duplicates for other statements
                stmt_clean = stmt.strip()
                if stmt_clean not in processed_statements:
                    processed_statements.add(stmt_clean)
                    sql_sections.append(stmt_clean + "\n\n")

    # Write output file
    with open(OUTPUT_SQL_PATH, 'w', encoding='utf-8') as f:
        f.writelines(sql_sections)
        
    print(f"Successfully generated master SQL file: {OUTPUT_SQL_PATH}")

if __name__ == "__main__":
    main()
